// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZtxmmXxGhI3PcceC9N439eETnXsEzE0',
    appId: '1:798475103944:web:d997e617929d0300cdbffd',
    messagingSenderId: '798475103944',
    projectId: 'instagramclone-bbec1',
    authDomain: 'instagramclone-bbec1.firebaseapp.com',
    storageBucket: 'instagramclone-bbec1.firebasestorage.app',
    measurementId: 'G-1JN8BXGKED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoN35Fo3iv1ujijWSEc4PcFJhV_fkzHFo',
    appId: '1:798475103944:android:1c582b39ad791637cdbffd',
    messagingSenderId: '798475103944',
    projectId: 'instagramclone-bbec1',
    storageBucket: 'instagramclone-bbec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1ZmdwkY5YM542WxaY1ZmMFZ4YPPn9gw',
    appId: '1:798475103944:ios:eee78ccd2e376f64cdbffd',
    messagingSenderId: '798475103944',
    projectId: 'instagramclone-bbec1',
    storageBucket: 'instagramclone-bbec1.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF1ZmdwkY5YM542WxaY1ZmMFZ4YPPn9gw',
    appId: '1:798475103944:ios:eee78ccd2e376f64cdbffd',
    messagingSenderId: '798475103944',
    projectId: 'instagramclone-bbec1',
    storageBucket: 'instagramclone-bbec1.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZtxmmXxGhI3PcceC9N439eETnXsEzE0',
    appId: '1:798475103944:web:624edafb359518f3cdbffd',
    messagingSenderId: '798475103944',
    projectId: 'instagramclone-bbec1',
    authDomain: 'instagramclone-bbec1.firebaseapp.com',
    storageBucket: 'instagramclone-bbec1.firebasestorage.app',
    measurementId: 'G-35VWB46BHV',
  );
}
